### ISSUE TITLE
Segfaults with empty content folder

### ISSUE THREAD

**Issue by vgmoose** [shinyquagsire23/makefst#1]
The game @Creepermario and I maintain, [Space Game](https://github.com/vgmoose/space/tree/wut), has [no content folder](https://github.com/vgmoose/space/tree/wut/space_game) as it's all OSScreen based and uses no external files. (The ELF has audio, but it hasn't implemented in the RPX yet, and all images are loaded as bitmap arrays as a carryover from browserhax)

When I first ran makefst, I created an empty "content" folder, as I thought it was required. This results in the following:
```
$ ./makefst -out space.woomy -icon space_game/meta/iconTex.tga -name "Space Game" -internal "space" space_game/
Compiling directory 'space_game' under TID 00050000505A4B00, Group Id 0x6D32, ver 0...
6 files, 10 entries total
Segmentation fault (core dumped)
```

Removing the empty content folder, or putting an empty file in that folder, allows the .woomy to be made successfully.

**Comment by shinyquagsire23** [comment]
Fixed 94c2eef8d8cf42910a496cb195846ea2507fdf3d
